### ISSUE TITLE
Traces older than query_ingesters_until are not (initially) returned in search with time range parameters

### ISSUE THREAD

**Issue by critchtionary** [grafana/tempo#3150] opened 2023-11-17 14:35 UTC
**Describe the bug**
We have a use case where we are hoping to send traces to Tempo asynchronously so they could reach Tempo up to a couple of hours after the end time of the trace. What we have found is that when the end time more than `query_ingesters_until` ago, the traces are not immediately queriable when the query is based on a time range (but they can be queried if time range is omitted, or if searching by Trace ID directly).

If I wait a further 30 minutes after sending the traces, the time range query starts working so I suspect it is related to `query_ingesters_until`

**To Reproduce**
1. Start Tempo (2.3.0, but also reproduced in 2.2.4) - use default `query_ingesters_until` value of 30m
2. Send in trace A with end time 28 minutes ago (doesn't matter if using GRPC or HTTP)
3. Send in trace B with end time 31 minutes ago
4. Query by trace IDs - both traces can be found
5. Search by service name - both traces can be found
6. Search by service name and set time range to last hour - **only trace A is returned**

Here is a script I have been using to reproduce this:

<details>

<summary>trace_template.json</summary>

```
{
	"resourceSpans": [{
    	"resource": {
        	"attributes": [{
            	"key": "service.name",
            	"value": {
                	"stringValue": "my.service"
            	}
        	}]
    	},
    	"scopeSpans": [{
        	"scope": {
            	"name": "my.library",
            	"version": "1.0.0",
            	"attributes": [{
                	"key": "my.scope.attribute",
                	"value": {
                    	"stringValue": "some scope attribute"
                	}
            	}]
        	},
        	"spans": [
        	{
            	"traceId": "",
            	"spanId": "",
            	"name": "I am a span!",
            	"startTimeUnixNano": 0,
            	"endTimeUnixNano": 0,
            	"kind": 2,
            	"attributes": [
            	{
                	"key": "my.span.attr",
                	"value": {
                    	"stringValue": "some value"
                	}
            	}]
        	}]
    	}]
	}]
}
```

</details>

<details>

<summary>reproducer.py</summary>

```
import json
import time

import requests

def set_span_details(trace, minutes_old, trace_id, span_id):
    span = trace["resourceSpans"][0]["scopeSpans"][0]["spans"][0]

    start_time = int((time.time() - (60 * minutes_old)) * 1_000_000_000)
    span["startTimeUnixNano"] = start_time
    span["endTimeUnixNano"] = start_time + 1

    span["traceId"] = trace_id
    span["spanId"] = span_id

    return trace

    
def send_trace(trace):
    headers = {"Content-type": "application/json"}
    requests.post("http://localhost:4318/v1/traces", json=trace, headers=headers)

def query_trace(trace):
    response = requests.get(f"http://localhost:3200/api/traces/{trace}")
    print(response.json())

with open('trace_template.json', 'r') as f:
    trace = json.load(f)

    # Older than query_ingesters_until
    old_trace_id = "7bba9f33312b3dbb8b2c2c62bb7abe2d"
    trace = set_span_details(trace, 31, old_trace_id, "086e83747d0e381e")
    send_trace(trace)

    # Newer than query_ingesters_until
    new_trace_id = "5b8aa5a2d2c872e8321cf37308d69df2"
    trace = set_span_details(trace, 28, new_trace_id, "93564f51e1abe1c2")
    send_trace(trace)

    # Give Tempo a chance to ingest traces
    time.sleep(10)

    query_trace(old_trace_id)
    query_trace(new_trace_id)

    # Search by service name
    service_query = "http://localhost:3200/api/search?tags=service.name%3Dmy.service"
    print(requests.get(service_query).json())

    # Search by service name and time range (last hour)
    end = int(time.time())
    start = end - (3600)
    print(start, end)
    print(requests.get(f"{service_query}&start={start}&end={end}").json())

```

</details>

<details>

<summary>Output</summary>

```
{'batches': [{'resource': {'attributes': [{'key': 'service.name', 'value': {'stringValue': 'my.service'}}]}, 'scopeSpans': [{'scope': {'name': 'my.library', 'version': '1.0.0'}, 'spans': [{'traceId': 'e7qfMzErPbuLLCxiu3q+LQ==', 'spanId': 'CG6DdH0OOB4=', 'name': 'I am a span!', 'kind': 'SPAN_KIND_SERVER', 'startTimeUnixNano': '1700229112728133120', 'endTimeUnixNano': '1700229112728133121', 'attributes': [{'key': 'my.span.attr', 'value': {'stringValue': 'some value'}}], 'status': {}}]}]}]}

{'batches': [{'resource': {'attributes': [{'key': 'service.name', 'value': {'stringValue': 'my.service'}}]}, 'scopeSpans': [{'scope': {'name': 'my.library', 'version': '1.0.0'}, 'spans': [{'traceId': 'W4qlotLIcugyHPNzCNad8g==', 'spanId': 'k1ZPUeGr4cI=', 'name': 'I am a span!', 'kind': 'SPAN_KIND_SERVER', 'startTimeUnixNano': '1700229292959897088', 'endTimeUnixNano': '1700229292959897089', 'attributes': [{'key': 'my.span.attr', 'value': {'stringValue': 'some value'}}], 'status': {}}]}]}]}

{'traces': [{'traceID': '5b8aa5a2d2c872e8321cf37308d69df2', 'rootServiceName': 'my.service', 'rootTraceName': 'I am a span!', 'startTimeUnixNano': '1700229292959897088'}, {'traceID': '7bba9f33312b3dbb8b2c2c62bb7abe2d', 'rootServiceName': 'my.service', 'rootTraceName': 'I am a span!', 'startTimeUnixNano': '1700229112728133120'}], 'metrics': {'inspectedTraces': 2, 'inspectedBytes': '9296', 'completedJobs': 1, 'totalJobs': 1}}

1700227383 1700230983

{'traces': [{'traceID': '5b8aa5a2d2c872e8321cf37308d69df2', 'rootServiceName': 'my.service', 'rootTraceName': 'I am a span!', 'startTimeUnixNano': '1700229292959897088'}], 'metrics': {'inspectedTraces': 2, 'inspectedBytes': '9896', 'completedJobs': 1, 'totalJobs': 1}}
```
</details>

**Expected behavior**
Trace B should be returned in time-based query. The last line of the output shows `'inspectedTraces': 2`, but only returned one trace despite them both being in the requested time range.

The [documentation](https://grafana.com/docs/tempo/latest/api_docs/#search) mentions that adding the time range changes how Tempo searches, but I don't take this to mean that the older trace would be omitted:
> Providing both start and end will change the way that Tempo searches. If the parameters are not provided, then Tempo will search the recent trace data stored in the ingesters. If the parameters are provided, it will search the backend as well.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Tanka - happens with both single-binary and microservices deployment

**Comment by joe-elliott** [comment] 2023-11-17 16:41
My guess is that the following config option is preventing them from being returned:

```
storage:
  trace:
    wal:
      ingestion_time_range_slack: 2m
```

We use the span timestamps to determine a start/end time for each block. When you do a search we only consider those blocks whose time ranges overlap with the search range.

However, when we first added search we found that some teams were sending spans with an empty timestamp and others were sending them years in the future. So what happened is that every block's start was years in the past and every block's end was years in the future. The end result is that every search hit every block.

So when we add a span to a block we only adjust the block start/end if it's span start/end are within the `ingestion_time_range_slack` above. Perhaps try setting that to 2h? 3h?

Since your issue seems related to ingesters and block flushing there may be more to this. Let's start with the above config option and see if that fixes the issue. Also, you can look at block start/ends in the backend storage as well as on the ingester disk to get a feel for the behavior I'm describing above.

**Comment by critchtionary** [comment] 2023-11-23 09:30
Setting `ingestion_time_range_slack` to 2h did change the outcome of my reproducer script: the 28 min old trace was still the only one returned by the time range query. I have also noticed that if I wait a couple of minutes (i.e. so that the more recent trace is now over 30 minutes old), neither of them are returned by the time range query.

Not exactly sure what I should be looking for regarding blocks. The ingester had a `meta.json` with this content:

```
{
  "format": "vParquet2",
  "blockID": "350b9a91-01f2-4b0f-91af-871e29a0f0fc",
  "minID": "W4qlotLIcugyHPNzCNad8g==",
  "maxID": "e7qfMzErPbuLLCxiu3q+LQ==",
  "tenantID": "single-tenant",
  "startTime": "2023-11-23T08:45:18Z",
  "endTime": "2023-11-23T08:48:19Z",
  "totalObjects": 2,
  "size": 0,
  "compactionLevel": 0,
  "encoding": "none",
  "indexPageSize": 0,
  "totalRecords": 0,
  "dataEncoding": "",
  "bloomShards": 0,
  "footerSize": 0
}
```

The traces were sent at 9:16:19 with end times of 8:45:18 and 08:48:19.

**Comment by joe-elliott** [comment] 2023-11-27 15:20
So it looks like your meta.json is set correctly. The spans were sent roughly half an hour in the past and the blocks meta indicates that with its start/end times.

Ok, digging deeper I am in growing agreement that the problem is with `query_ingesters_until`. If you are setting your time range to the previous hour the ingesters won't be queried at all b/c the frontend will only create jobs for the blocks. However, in your case, you do have valid traces/spans you want to find in the ingesters.

Here is where we build the search request for the ingesters:

https://github.com/grafana/tempo/blob/c00e7ef1103a8e7804b6f71fe8e90d0a2d9a9b02/modules/frontend/searchsharding.go#L127

We return nil from this func (meaning no ingester request) if the time range is before `query_ingesters_until`. In order to push spans that are several hours old and reliably search for them you will need to set both `query_ingesters_until` and `ingestion_time_range_slack`.

We should likely update the docs to indicate the interaction between these settings for operators who want this kind of setup. After you confirm these changes make Tempo work as expected we'll work on a PR.

cc @knylander-grafana

**Comment by critchtionary** [comment] 2023-11-28 11:41
If I change `query_ingesters_until` and `ingestion_time_range_slack` to `2h` then the time range query returns both traces which is my desired state.

I noticed that if I only set `query_ingesters_until` (leaving `ingestion_time_range_slack` as the default), and send in my traces, the block end time is less than the start time:

```
{
  "format": "vParquet2",
  "blockID": "e4ec20b1-7d22-41cf-bbad-cf44d1431270",
  "minID": "W4qlotLIcugyHPNzCNad8g==",
  "maxID": "e7qfMzErPbuLLCxiu3q+LQ==",
  "tenantID": "single-tenant",
  "startTime": "2023-11-28T11:36:36Z",
  "endTime": "2023-11-28T11:08:33Z",
  "totalObjects": 2,
  "size": 0,
  "compactionLevel": 0,
  "encoding": "none",
  "indexPageSize": 0,
  "totalRecords": 0,
  "dataEncoding": "",
  "bloomShards": 0,
  "footerSize": 0
}
```

**Comment by joe-elliott** [comment] 2023-11-28 18:28
> , the block end time is before the start time:

Yeah, that logic is not great and I'm not totally surprised you could work it into a bad state. Does this happen regularly or rarely?

If the original issue is resolved, I'd like to close this and create a new issue focused on the block start/end time.

**Comment by joe-elliott** [comment] 2023-11-30 17:58
Going to go ahead and close this issue in favor of the linked one above. Thanks for reporting the problem!

**Closed by joe-elliott** 2023-11-30 17:58 UTC
