### ISSUE TITLE
failed DNS SRV record lookup errors on querier container

### ISSUE THREAD

**Issue by trexx** [grafana/tempo#1248] opened 2022-01-25 15:37 UTC
**Describe the bug**
Getting DNS errors in the querier container.
`caller=dns_resolver.go:209 msg="failed DNS SRV record lookup" err="lookup _grpclb._tcp.grafana-tempo-tempo-distributed-query-frontend-discovery on 10.161.128.10:53: no such host"`

These errors started upon upgrading to 1.3.0

**To Reproduce**
Deployed tempo-distributed 0.15.0 helm chart.
View logs of querier container.

**Expected behavior**
No DNS errors.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Additional Context**
The frontend-discovery service has no such grpclb port defined in the helm chart.
I have verified the rendered configuration to be: 
```
    querier:
      frontend_worker:
        frontend_address: grafana-tempo-tempo-distributed-query-frontend-discovery:9095
```
I have seen references to grpclb in loki helm charts listening on port 9096 however I see no such references in the tempo-distributed helm charts.

Related:
https://github.com/grafana/helm-charts/pull/803
https://github.com/grafana/helm-charts/issues/801

I am not sure if this is a helm chart issue or an issue with tempo.

**Comment by joe-elliott** [comment] 2022-01-25 18:21
We are seeing this error logged as well in our internal cluster which is deployed with jsonnet. Does querying work for you?

Querying works in our clusters and I smoke tested the helm chart as well to confirm basic read/writing worked. I will slot this for 1.4.

Hopefully it's just cleaning up an innocuous error log?

**Comment by trexx** [comment] 2022-01-26 07:50
Yes querying works, and for the most part it seems everything is working fine.

**Comment by joe-elliott** [comment] 2022-01-26 13:49
> Yes querying works, and for the most part it seems everything is working fine.

Thanks for the issue. We will look at cleaning up the log when we can :+1:

**Comment by annanay25** [comment] 2022-01-27 10:22
I had made a note of this somewhere but I guess I lost it. This might be related: https://github.com/grafana/dskit/pull/102

**Comment by kasunsjc** [comment] 2022-01-27 18:26
Having the same issue when using tempo with microservice helm deployment

**Comment by linhuatan** [comment] 2022-01-29 11:55
Having the same issue when using tempo with microservice helm deployment

I see the following similar errors as well from injector and distributers
`level=info ts=2022-01-29T11:44:31.027387198Z caller=dns_resolver.go:209 msg="failed DNS SRV record lookup" err="lookup _grpclb._tcp.tempo-tempo-distributed-query-frontend on 10.18.128.10:53: no such host"`

**Comment by Denissa89** [comment] 2022-01-31 07:35
Hello! I encountered a similar error when upgrading to tempo 1.3 from the helm-chart [tempo-distributed](https://github.com/grafana/helm-charts/tree/main/charts/tempo-distributed)
```
level=info ts=2022-01-31T07:34:32.789371071Z caller=dns_resolver.go:209 msg="failed DNS SRV record lookup" err="lookup _grpclb._tcp.tempo-tempo-distributed-query-frontend-discovery on 10.210.0.10:53: no such host"
```

**Comment by sherifkayad** [comment] 2022-02-07 08:47
Same here! .. Any plans when that log can be cleaned up / what the clear reason of the error is?

**Comment by joe-elliott** [comment] 2022-02-07 13:07
This should be removed in 1.4. At the moment we are unsure of the cause. See @annanay25 's comment above on the change that may have started the issue.

**Comment by joe-elliott** [comment] 2022-03-02 20:44
We have not seen this in our clusters fora few weeks. It appears to have been fixed in the r31 release when we upgraded dskit.

https://github.com/grafana/tempo/compare/r30..r31

![image](https://user-images.githubusercontent.com/2272392/156446618-523ea698-3e04-40d3-8406-92844dc09ef4.png)

**Closed by joe-elliott** 2022-03-02 20:44 UTC

**Comment by tayfourius** [comment] 2022-03-10 07:57
I fixed the issue with adding the port 
`    - name: grpclb
      port: 9096
      targetPort: grpc
      protocol: TCP
`
to tempo-distributed-query-frontend service and tempo-distributed-query-frontend-discovery service

`apiVersion: v1
kind: Service
metadata:
  name: tempo-distributed-query-frontend-discovery
  namespace: logging
  labels:
    helm.sh/chart: tempo-distributed-0.16.4
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo-distributed
    app.kubernetes.io/version: "1.3.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: query-frontend
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 3100
      targetPort: 3100
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: 9095
    - name: tempo-query-jaeger-ui
      port: 16686
      targetPort: 16686
    - name: tempo-query-metrics
      port: 16687
      targetPort: jaeger-metrics
    - name: grpclb
      port: 9096
      targetPort: grpc
      protocol: TCP  
  selector:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo-distributed
    app.kubernetes.io/component: query-frontend
`
