### ISSUE TITLE
[Trace Explorer] Auto completion on `status` values suggests erroneous `0` and `2`

### ISSUE THREAD

**Issue by cyrille-leclerc** [grafana/tempo#2248] opened 2023-03-21 23:15 UTC
**Describe the bug**

Auto completion on `status` values not only suggests the valid values `ok`, `error`, and `unset` but also suggests erroneous values `0` and `2`.

When using `status = 0` or `status = 2`, the query returns the error `upstream: (500) binary operations must operate on the same type: status = 2`

Values `0`, `1`, and `2` seem to be leaks of the enum values of `unset=0`, `ok=1`, and `error=2` (eg [here](https://opentelemetry-python.readthedocs.io/en/latest/api/trace.status.html)).

<img width="584" alt="image" src="https://user-images.githubusercontent.com/459691/226762387-e22ce10f-f1f0-4ee6-9601-557ec1201378.png">

**Environment:**
 - Grafana Cloud Traces as of 2023-03-22

**Comment by mapno** [comment] 2023-03-22 11:19
I think this is a duplicate of https://github.com/grafana/tempo/issues/2200. It should be fixed now with https://github.com/grafana/tempo/pull/2219.

**Comment by 09jvilla** [comment] 2023-03-23 03:59
Closing as duplicate.

**Closed by 09jvilla** 2023-03-23 03:59 UTC
Labels: type/bug
