### ISSUE TITLE
Tempo returns 500s for some 400s

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#568] opened 2021-03-04 18:28 UTC
**Describe the bug**
The Tempo query-frontend sharding code will hide certain errors (like 429) and instead incorrectly return 500.

**Comment by annanay25** [comment] 2021-03-05 13:29
After some investigation, my conclusions are -
- the query frontend has always been reporting a 429
- the problem is that we're not checking `resp.StatusCode`  in the plugin in tempo-query here - https://github.com/grafana/tempo/blob/1cbfc21fd76faa0e16b2dcb9401290f89165ae31/cmd/tempo-query/tempo/plugin.go#L63
- on hitting resource limits, `resp.StatusCode` there is seen to be `429` and `resp.Body` is `rpc error: code = Code(429) desc = too many outstanding requests`  but we're trying to parse it like a otlp trace batch.. and so its actually tempo-query that's throwing the 500

Next steps -
- Add check on response status code in tempo-query
- We expect #382 to be fixed soon, and so error handling will switch over to Grafana

**Comment by annanay25** [comment] 2021-03-18 14:51
This is fixed by #574

**Closed by annanay25** 2021-03-18 14:51 UTC
