### ISSUE TITLE
Small Multipart Errors with Parquet

### ISSUE THREAD

**Issue by amitsetty** [grafana/tempo#1769] opened 2022-09-28 17:48 UTC
**Describe the bug**

Last block created by compactor is statistically small since the final block is shipped to the backend regardless of its size. 

This leads to final blocks statistically being under 5MB because the compact cycle remainder is shipped regardless of its size.
The outcome is that when using s3 and parquet the following error happens statistically
```
msg="error during compaction cycle" err="error shipping block to backend: error completing multipart upload, object: single-tenant/***, obj etag: : Your proposed upload is smaller than the minimum allowed object size."
```

**To Reproduce**
1. Start Tempo using parquet
2. Use an S3 backend

**Expected behavior**
The compactor should not have statistical errors when using parquet

**Additional Context**
Related to Issue #306
My understanding is that the impact of this is that the final blocks are not being compacted in these cases but also all blocks compacted in the compaction cycle are not marked as compacted even though they have already been flushed.

Sure you guys would have a better understanding how to handle this but some things that come to mind are 
1) Flush last block as final multipart (not sure what the side effects of this are)
2) Leave the final block for the next compaction cycle (not sure what this entails)
3) Always hold 2 blocks in order to flush the last 2 together each taking half the buffer (seems less elegant)

In addition I think we should probably rethink the error situation so that an error with one upload won’t lead to not marking compacted blocks as compacted

Seems like this is where the issue is occurring
[https://github.com/grafana/tempo/blob/97dbd7ccd8dc253991738ae33a0721dbb87edce7/tempodb/encoding/vparquet/compactor.go#L203](url)

**Comment by joe-elliott** [comment] 2022-09-28 21:05
When compacting parquet blocks we flush a segment to the backend everytime we cut a row group. I'm surprised we're not seeing this internally. It does make sense that the final rowgroup would occasionally be < 5MB.

Our current setting is:

```
storage:
    trace:
        block:
            row_group_size_bytes: 2e+08
```

The tip of main logic is a bit wonky in that the actual row group size it will cut is actually quite a bit smaller than that 30-40MB. I do believe the row_group_size_bytes default is 30MB which would occasionally cut row groups < 5MB.

**Comment by amitsetty** [comment] 2022-09-28 21:39
Occasionally meaning 1/6 of the time at default setting. #Meaning 1/6 of the time all blocks are flushed twice aside from the last since they aren’t flagged as compacted

Strange to hear you guys haven’t been experiencing this also 

Also our average block is cut around 35MB which seems a bit above the 30MB rather than below in our case

**Comment by ie-pham** [comment] 2022-10-03 18:38
Could you try increasing row_group_size_bytes to ~100MB and see that helps?

**Comment by amitsetty** [comment] 2022-10-03 18:43
I can but I don't understand how that will get rid of the issue. 
It seems that that will just lead the issue to happen 5% of the time instead of 1/6 of the time because it will lead the remainder block to have a 1/20 chance of being between 1 and 5 MB.

**Comment by ie-pham** [comment] 2022-10-03 22:02
Thank you! There is a known bug on our side regarding row group size. However, we do not believe this issue has to do with the final block being under 5MB, but somewhere else in the process, as we do not see this error in our clusters. With your help we could triage it further and get this issue fixed.

**Comment by ie-pham** [comment] 2022-10-12 14:19
This is great news! We will continue to work on outside to fix the known issue revolving around row group size and update one that work is completed.

**Comment by mdisibio** [comment] 2022-10-19 17:52
Adding a few thoughts.  I believe the root cause is that the calculations in [estimateTraceSize](https://github.com/grafana/tempo/blob/main/tempodb/encoding/vparquet/create.go#L219) is not correct for the size on disk for the trace in parquet format.  Previously the compactor used the number of `parquet.Value`s written in raw form to [flush](https://github.com/grafana/tempo/blob/f7762e53efb2cf1f6be9beb5dbe8923abcab838c/tempodb/encoding/vparquet/compactor.go#L163) and it was more accurate, because of parquet dictionary/delta/RLE encodings and compression, actual disk size approaches 1-byte-per-value or less. `estimateTraceSize` is capturing the full length of strings, int64s, etc. Therefore it makes sense that it would overestimate by quite a bit, and a target of 30MB could yield a flush under 5MB. 

Ideally, I think we make the following changes:
1. Update `estimateTraceSize` to calculate differently. All ints are estimated at 1 byte regardless of width.  All non-null strings are estimated at 1 byte (Tempo uses dictionary encoding for all string columns).   
2. [StreamingBlock.Flush](https://github.com/grafana/tempo/blob/main/tempodb/encoding/vparquet/create.go#L163) cuts the rowgroup and flushes the data to the backend at the same time.  This 1:1 actino seems like a design flaw, and we should fix this by disconnecting row group flush from backend flush.   Let's change StreamingBlock.Flush to conditionally flush the buffered writer only if it has enough data too. This is accessible with `b.bw.Len()`.   The simplest is to probably pass the same rowGroupSizeBytes to the StreamingBlock on creation.

**Comment by mdisibio** [comment] 2023-01-13 13:36
I believe this was fixed by https://github.com/grafana/tempo/pull/1873

**Comment by joe-elliott** [comment] 2023-01-24 20:58
> I believe this was fixed by https://github.com/grafana/tempo/pull/1873

Agreed. Closing.

**Closed by joe-elliott** 2023-01-24 20:58 UTC
