### ISSUE TITLE
Expose Tempo version through an `/api/...` endpoint

### ISSUE THREAD

**Issue by fabrizio-grafana** [grafana/tempo#2683] opened 2023-07-21 11:57 UTC
**Is your feature request related to a problem? Please describe.**
Currently, it seems there is no way to retrieve in Grafana the version of the Tempo instance that a user is running. See the related [GitHub issue in the Grafana repo](https://github.com/grafana/grafana/issues/67660).

**Describe the solution you'd like**
The Tempo (backend) version is available to Grafana (frontend). The discussed solution on the Slack channel is to expose it using an `/api/...` endpoint, e.g., `/api/status/version`, similar to what is done by Loki, Mimir, and Prometheus.

**Describe alternatives you've considered**
- Use other endpoints to retrieve the same information. There is the `status/version` endpoint, but it can't be access through the browser.
- Use a proxy to call `status/version`: Grafana frontend would call a backend that acts as a proxy for Tempo and call `status/version`.

**Additional context**
We would use this endpoint to know which features to enable in Grafana. Dummy example: if a user is using version `N` of Tempo and a certain version of Grafana that needs a Tempo endpoint exposed only from version `M`>`N` onwards of Tempo, we can hide that feature in Grafana until the user does not upgrade Tempo.

**Comment by joe-elliott** [comment] 2023-07-21 12:55
Why can `/status/version` not be called?

**Comment by fabrizio-grafana** [comment] 2023-07-24 11:15
It seems only endpoints exposed with prefix `api` can be called. A couple of us in Traces and Profiling tried to call `/status/version`, but we can hit it only locally and not from remote/cloud environments. Also Loki, Mimir, and Prometheus seem to follow this approach, as we were discussing on Slack Tempo's channel. 

Do you know a way to actually hit `/status/version` from Grafana frontend? Maybe we are missing something simple. If not, we discussed internally in the squad to investigate this a little more, potentially also asking the Hosted Grafana team for more context.

**Comment by joe-elliott** [comment] 2023-07-24 14:11
The issue is in our internal gateway. It only routes specific paths. Even if we added an `/api/version` it would not be accessible until we added it there.

**Comment by fabrizio-grafana** [comment] 2023-07-25 12:27
Got it! 

Do you see any problem in enabling that endpoint in our internal gateway, either as `/status/version` or `/api/status/version`, whatever is easier, so that we can access it? If that's OK, in our squad were thinking to ask Grafana SaaS if and how we can do that, I can take of asking.

**Comment by joe-elliott** [comment] 2023-07-25 19:32
Closing this issue in favor of https://github.com/grafana/tempo/issues/2387

Added some details in the final comment about what we want to implement.

**Closed by joe-elliott** 2023-07-25 19:32 UTC
Labels: backend
