### ISSUE TITLE
Tempo Ingester Flushes Failing 

### ISSUE THREAD

**Issue by inbarpatashnik** [grafana/tempo#2034] opened 2023-01-31 11:03 UTC
Ever since updating tempo version to be in line with the main branch (commit for PR #1997) we have been getting the follow alert

TempoIngesterFlushesFailing

Any idea why this might be happening? 

(Before this we were running on a previous version of main from a few months ago. The only changes made to the configuration were the image tag and getting rid of the max_bytes feature flag from the increasing storage bug which was solved) 
![AB895088-9776-4EFF-B7A4-4C08FBCD70D8](https://user-images.githubusercontent.com/75210443/215742615-cf57ca80-18b1-4eaa-bbcd-f48ffa72fc75.jpeg)

**Comment by inbarpatashnik** [comment] 2023-01-31 17:22
I saw an error message that said 
failed to cut traces because storage is full.
I assumed that it refers to the PVC which is getting full because there are no flushes?
So I struggle to find the problem :(

**Comment by joe-elliott** [comment] 2023-01-31 17:28
If you can share the exact text of the log messages as well as a config, I may be able to help you with this issue. As is, it is difficult to make guesses based on this information.

**Comment by inbarpatashnik** [comment] 2023-01-31 17:43
![Uploading 2BBFB754-799B-4E99-92CA-B9FB6E12580E.jpeg…]()

**Comment by inbarpatashnik** [comment] 2023-01-31 17:44
level-error ts=2023-01-30T13:33:25.50724828Z caller-flush.go:156 org_id=single-tenant msg="failed to cut traces"

err="error closing writer: writing buffered pages of row group column 0: write

/var/tempo/wal/8d2d8482-6807-4b71-bb54-b78c0ebd1e68+single-tenant+vP: no space left on device"

**Comment by joe-elliott** [comment] 2023-01-31 17:59
It appears that you've run out of space on your PVC. I would recommend increasing it.

**Comment by inbarpatashnik** [comment] 2023-01-31 18:08
The thing is that the PVC is getting full because the flushes are failing.
Ever since we upgraded to branch main and removed the flag I mentioned above, the flushes didn't succeed and because of that the PVC's storage was getting full.
I saw that it used to get to about 20% of its space until the flushes occurred and now it gets to 100% and flushes always fail, even when the storage is still not full (I didn't see any error message in this case).
We also tried to use the renamed flag, parquet_max_bytes, but it still didn't help.

**Comment by mdisibio** [comment] 2023-01-31 18:25
Hi, can you check the logs for the below messages?  These should indicate the root cause error when flushes are failing:

* `error performing op in flushQueue`
* `error copying block from local to remote backend`

**Comment by inbarpatashnik** [comment] 2023-02-01 18:55
Maybe do you know why its happening and how it can be fixed?😊

> @mdisibio found one of the errors you mentioned!
> _level=error ts-2023-01-31T18:57:46.3113943352 caller-flush.go:221 org_id=single-tenant msg="**error performing op in flushQueue**" op=0 block=0c5b727f-a2f1-4a2c-ae13-9c508d875c45 attempts 1 err="error clearing completing block: unlinkat /var/tempo/wal/0c5b7271-a2f1-4a2c-ae13-9c508d875c45+single-tenant+vParquet: directory not empty"_

**Comment by joe-elliott** [comment] 2023-02-01 19:02
Can you confirm that you are running low on disk space? An increase in ingestion may have coincided with your upgrade or perhaps that upgrade used slightly more disk space and pushed your PVCs over the edge. We are unaware of any large changes to ingester disk usage.

My recommendation is to increase your disk sizes and monitor free space to prevent future occurences.

**Comment by kostya9** [comment] 2023-02-27 16:21
I have bumped into the same issue
```
level=error ts=2023-02-27T16:16:57.148676605Z caller=flush.go:221 org_id=single-tenant msg="error performing op in flushQueue" op=0 block=76fe43c1-5725-4f2b-a5b1-26ac1a03e6a3 attempts=1 err="error clearing completing block: unlinkat /var/tempo/wal/76fe43c1-5725-4f2b-a5b1-26ac1a03e6a3+single-tenant+vParquet: directory not empty"
```
And looks like there is a `.nfs***` file there. Looks like this file is created whenever a process is opening a file on a network storage. Does Tempo close all files it opens?

![image](https://user-images.githubusercontent.com/3115913/221619853-403013c9-319f-45d0-a0a6-3fe586ddd2e9.png)

![image](https://user-images.githubusercontent.com/3115913/221619560-0cbb0b56-3a9f-47a4-842f-493318c8446d.png)

**Comment by kostya9** [comment] 2023-02-27 22:18
@joe-elliott I found that the WAL block file is not closed before deleting the folder as far as I understood the code. This could make the NFS think that it's in use, and leave that .nfs file. Attempted fix here - https://github.com/grafana/tempo/pull/2152

**Comment by inbarpatashnik** [comment] 2023-02-28 10:30
Hi😊
When I checked there were files in this path

**Comment by kostya9** [comment] 2023-03-03 08:38
Looks like these .nfs files are created in the scope of "silly rename". This operation is to keep open files alive (for the duration that they are open) when they are unlinked (deleted). The newer NFS standard has some flags that work differently, but they are not implemented yet AFAIK. More info here - https://linux-nfs.org/wiki/index.php/Server-side_silly_rename

For tempo, this means that it deleted the files while they are open and then fails to delete the directory due to this "silly renamed" .nfs file.

I was hoping to test whether https://github.com/grafana/tempo/pull/2152 helps. When that will be merged, is there a CI process that builds a tempo container from the main branch, so that I can take that and use it? If yes, please advise me on the location where it is.

However, I am not sure because currently Parquet files are not closed too and I am not sure how to fix that in Tempo(https://github.com/grafana/tempo/issues/2153). That may require new APIs (e.g. `Close`) in the `parquet.File` type upstream.

And maybe there could be other safeguards too (e.g. retry flushes, continue to flush even if delete failed, retry only deletes etc.) that help with this kind of situation?

**Comment by joe-elliott** [comment] 2023-03-03 15:48
Thanks for the link. So NFS is renaming the file b/c Tempo made an unlink call to it, but still had a handle open? I think this is starting to make sense now. Agree #2152 is a good candidate for cleanup. Let's get that merged (it's very close) then we can test if it fixes this issue.

> is there a CI process that builds a tempo container from the main branch, so that I can take that and use it? If yes, could you please advise me on the location where it is published to?

Yup, tip of main is automatically built to here: 
https://hub.docker.com/r/grafana/tempo/tags

![image](https://user-images.githubusercontent.com/2272392/222763955-3d35c3fa-7c06-4eb1-8108-a146cfaa121c.png)

> However, I am not sure that it will 100% help because currently Parquet files are not closed too

In #2152 I think we came to an agreement on a pattern to allow the various methods (Fetch, SearchTags, etc.) to correctly close the os.File.

> That may require new APIs (e.g. Close) in the parquet.File type upstream.

Closing the os.File should be sufficient.

> And maybe there could be other safeguards too (e.g. retry flushes, continue to flush even if delete failed, retry only deletes etc.) that help with this kind of situation?

We support retries on other queue operations. I would be fine with adding code to retry block clear.

**Closed** 2023-03-08 13:47 UTC

**Comment by kostya9** [comment] 2023-03-09 20:30
Reporting back - after #2152 I don't see failed flushed anymore, the space used looks OK (no more hundreds of gigs in WAL folder), and search tags perf is much better (sometimes takes a couple of hundred milliseconds, sometimes takes several seconds, but it doesn't timeout anymore at all). Everything looks good!

![image](https://user-images.githubusercontent.com/3115913/224148640-2e61711d-e63b-4950-ad7c-be92817f608d.png)

Thanks for the assistance!

**Comment by joe-elliott** [comment] 2023-03-09 20:44
This is great news! Excellent work identifying the issue and getting a fix in. That was not an easy one to track down.
