### ISSUE TITLE
Disaster Recovery details

### ISSUE THREAD

**Issue by pdeva** [grafana/tempo#310] opened 2020-11-02 20:21 UTC
The docs dont talk much about DR.
If i understand this correctly:

Tempo batches writes onto the local filesystem first. Then it pushes that batch onto s3.
if the instance dies before that batch is pushed, that data is gone.

What are the suggested workarounds for this?

**Comment by joe-elliott** [comment] 2020-11-03 01:53
Only traces that are currently being appended to are kept in memory.  If an ingester receives SIGTERM it will flush these to disk and on restart will reload them and nothing will be lost.  If an ingester unexpectedly restarts it will lose the in memory traces.

To handle this situation it is recommended to use a replication factor > 1.  At Grafana we use a RF of 2 with a write consistency of 1.  A second option is RF of 3 which will enable quorum reads/writes.

Regarding RF 2.  I believe that the write path is functioning as intended but I'm suspicious the read path is not.  See #284.  It is something we are actively working on.

**Comment by joe-elliott** [comment] 2020-11-10 15:51
Thank you for the question.  Closing to clean things up!

**Closed by joe-elliott** 2020-11-10 15:51 UTC
