### ISSUE TITLE
Unhealthy compactors do not leave the ring after rollout

### ISSUE THREAD

**Issue by gravelg** [grafana/tempo#1081] opened 2021-10-26 20:45 UTC
**Describe the bug**
When rolling out a new deployment of the compactors, some old instances will remain in the ring as Unhealthy. The only fix seems to be to port-forward one of the compactors and use the `/compactor/ring` page to "Forget" all the unhealthy instances.

**To Reproduce**
1. Start Tempo in kubernetes (we have tried the 1.1 release but the issue persists with `af34e132a1b8`)
2. Perform a rollout of the compactors

**Expected behavior**
The compactors from the previous deployment leave the ring correctly

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: `kubectl apply`

**Additional Context**
We do not see this happen all the time. On one of our similarly sized but less busy clusters, old compactors rarely stay in the ring after a rollout. On the busier cluster, we had 14 unhealthy compactors from a previous deployment still in the ring, out of 30 in the deployment.

Our tempo config for memberlist:
```
memberlist:
      abort_if_cluster_join_fails: false
      join_members:
        - tempo-gossip-ring
      dead_node_reclaim_time: 15s
      bind_addr: ["${POD_IP}"]
```

Sample logs from a compactor that stayed in the ring as unhealthy, from the moment where shutdown was requested:
```
level=info ts=2021-10-26T15:26:54.628754652Z caller=signals.go:55 msg=""=== received SIGINT/SIGTERM ===\n*** exiting""level=info ts=2021-10-26T15:26:54.629120545Z caller=lifecycler.go:457 msg=""lifecycler loop() exited gracefully"" ring=compactor
level=info ts=2021-10-26T15:26:54.629162701Z caller=lifecycler.go:768 msg=""changing instance state from"" old_state=ACTIVE new_state=LEAVING ring=compactor
level=info ts=2021-10-26T15:26:55.632049563Z caller=lifecycler.go:509 msg=""instance removed from the KV store"" ring=compactor
level=info ts=2021-10-26T15:26:55.63212068Z caller=module_service.go:96 msg=""module stopped"" module=compactor
level=info ts=2021-10-26T15:26:55.632206675Z caller=module_service.go:96 msg=""module stopped"" module=overrides
level=info ts=2021-10-26T15:26:55.632206876Z caller=memberlist_client.go:572 msg=""leaving memberlist cluster""
level=info ts=2021-10-26T15:26:55.632249778Z caller=module_service.go:96 msg=""module stopped"" module=store
level=warn ts=2021-10-26T15:27:05.735678769Z caller=memberlist_client.go:587 msg=""broadcast messages left in queue"" count=16 nodes=146
level=info ts=2021-10-26T15:27:07.192768676Z caller=module_service.go:96 msg=""module stopped"" module=memberlist-kv
level=info ts=2021-10-26T15:27:07.194383366Z caller=server_service.go:50 msg=""server stopped""
level=info ts=2021-10-26T15:27:07.194466883Z caller=module_service.go:96 msg=""module stopped"" module=server
level=info ts=2021-10-26T15:27:07.19452497Z caller=app.go:271 msg=""Tempo stopped""
level=info ts=2021-10-26T15:27:07.194539895Z caller=main.go:135 msg=""Tempo running""
```
I was confused by that last `Tempo running` line but looking at the code in main.go, this seems normal.

**Comment by joe-elliott** [comment] 2021-10-29 18:46
So we have assigned this issue to 1.3 and will explore using the new ring, but in the interest of trying to recreate it can people share how they are deploying:  jsonnet, tempo-distributed helm, or custom?

I'd also be interested to know what backend people are using: s3, gcs, azure.

**Comment by gravelg** [comment] 2021-11-01 14:24
We're using a custom deployment method (homegrown templating mechanism) and using gcs for storage

**Comment by creinheimer** [comment] 2021-11-01 14:30
Hi Joe, we are using the following configuration:
- helm tempo-distributed-0.9.14
- aws s3 as storage

**Comment by joe-elliott** [comment] 2021-12-01 15:45
So, we have just seen this for the first time. It occurred when we rolled the compactors twice within ~60s of each other. This is not something we would do normally and may be the cause of the issue. Is this consistent with what others are seeing?

**Comment by gravelg** [comment] 2021-12-01 15:48
On our end, we see the issue when doing a single rollout of the compactors.

**Closed** 2021-12-16 17:13 UTC
