### ISSUE TITLE
Noisy error log in frontend processor - "transport is closing"

### ISSUE THREAD

**Issue by mnadeem** [grafana/tempo#493] opened 2021-01-30 15:53 UTC
**Tempo backend not ready to receive traffic even after hours**

Probably due to the following
````
level=error ts=2021-01-30T15:47:14.273319231Z caller=frontend_processor.go:61 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"
````

**Full Log**
````
level=info ts=2021-01-30T15:45:53.905814194Z caller=main.go:89 msg="Starting Tempo" version="(version=c189e23e, branch=master, revision=c189e23e)"
--
  | level=info ts=2021-01-30T15:45:54.258823037Z caller=server.go:229 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
  | level=info ts=2021-01-30T15:45:54.260118522Z caller=frontend.go:24 msg="creating tripperware in query frontend to shard queries"
  | level=warn ts=2021-01-30T15:45:54.260443879Z caller=modules.go:140 msg="Worker address is empty in single binary mode.  Attempting automatic worker configuration.  If queries are unresponsive consider configuring the worker explicitly." address=127.0.0.1:9095
  | level=info ts=2021-01-30T15:45:54.26054227Z caller=worker.go:112 msg="Starting querier worker connected to query-frontend" frontend=127.0.0.1:9095
  | ts=2021-01-30T15:45:54Z level=info msg="OTel Shim Logger Initialized" component=tempo
  | level=info ts=2021-01-30T15:45:54.261646095Z caller=module_service.go:58 msg=initialising module=memberlist-kv
  | level=info ts=2021-01-30T15:45:54.261675553Z caller=module_service.go:58 msg=initialising module=overrides
  | level=info ts=2021-01-30T15:45:54.261691519Z caller=module_service.go:58 msg=initialising module=store
  | level=info ts=2021-01-30T15:45:54.26172941Z caller=module_service.go:58 msg=initialising module=server
  | level=info ts=2021-01-30T15:45:54.263537314Z caller=module_service.go:58 msg=initialising module=ring
  | level=info ts=2021-01-30T15:45:54.263580354Z caller=module_service.go:58 msg=initialising module=ingester
  | level=info ts=2021-01-30T15:45:54.26361552Z caller=module_service.go:58 msg=initialising module=compactor
  | level=info ts=2021-01-30T15:45:54.263636317Z caller=module_service.go:58 msg=initialising module=query-frontend
  | level=info ts=2021-01-30T15:45:54.26381546Z caller=module_service.go:58 msg=initialising module=querier
  | level=info ts=2021-01-30T15:45:54.263859051Z caller=module_service.go:58 msg=initialising module=distributor
  | level=info ts=2021-01-30T15:45:54.263973679Z caller=worker.go:192 msg="adding connection" addr=127.0.0.1:9095
  | level=info ts=2021-01-30T15:45:54.264012639Z caller=ingester.go:278 msg="beginning wal replay" numBlocks=0
  | level=info ts=2021-01-30T15:45:54.263814539Z caller=compactor.go:95 msg="waiting for compaction ring to settle" waitDuration=1m0s
  | level=info ts=2021-01-30T15:45:54.264449966Z caller=lifecycler.go:521 msg="not loading tokens from file, tokens file path is empty"
  | level=info ts=2021-01-30T15:45:54.26545844Z caller=client.go:242 msg="value is nil" key=collectors/ring index=1
  | level=info ts=2021-01-30T15:45:54.266328848Z caller=lifecycler.go:550 msg="instance not found in ring, adding with no tokens" ring=ingester
  | level=info ts=2021-01-30T15:45:54.266478004Z caller=lifecycler.go:397 msg="auto-joining cluster after timeout" ring=ingester
  | ts=2021-01-30T15:45:54Z level=info msg="No sampling strategies provided, using defaults" component=tempo
  | level=info ts=2021-01-30T15:45:54.267568344Z caller=app.go:212 msg="Tempo started"
  | level=info ts=2021-01-30T15:46:54.265244168Z caller=compactor.go:97 msg="enabling compaction"
  | level=info ts=2021-01-30T15:46:54.265316073Z caller=tempodb.go:278 msg="compaction and retention enabled."
  | level=error ts=2021-01-30T15:47:14.273319231Z caller=frontend_processor.go:61 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"
  | level=error ts=2021-01-30T15:47:14.273303551Z caller=frontend_processor.go:61 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"
  | level=error ts=2021-01-30T15:47:14.273303003Z caller=frontend_processor.go:61 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"
  | level=error ts=2021-01-30T15:47:14.27332587Z caller=frontend_processor.go:61 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"
  | level=error ts=2021-01-30T15:47:14.273321788Z caller=frontend_processor.go:61 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"

````

![image](https://user-images.githubusercontent.com/476145/106360839-cdfe8b80-6340-11eb-89ae-ad226cc44df7.png)

**To Reproduce**
1. Start Tempo (grafana/tempo:latest) , as per the blog https://reachmnadeem.wordpress.com/2021/01/30/distributed-tracing-using-grafana-tempo-jaeger-with-amazon-s3-as-backend-in-openshift-kubernetes/

**Expected behavior**

Tempo backend should be ready to receive traffic

**Environment:**
 - Infrastructure: [Kubernetes, Openshift]
 - Deployment tool: [Jenkins Pipeline]

**Additional Context**

**Comment by joe-elliott** [comment] 2021-01-30 20:03
This error is due to the query worker not being able to connect to the frontend in single binary mode.  The query-frontend is a recent addition to Tempo and may still have some issues to work out.  Can you repro this error in 0.5.0?

@annanay25 can you take a look when you get a chance sometime this week?

**Comment by mnadeem** [comment] 2021-01-31 01:27
0.5.0 seems to  be working like a charm

**Comment by annanay25** [comment] 2021-02-01 15:10
Some thoughts on taking a closer look -

1) At first it looked like a connectivity issue between the querier and query frontend, but I see this log line -
```
  | level=info ts=2021-01-30T15:45:54.263973679Z caller=worker.go:192 msg="adding connection" addr=127.0.0.1:9095
```
which indicates the connection was added, so now I'm confused. If it is possible to connect to the metrics endpoint, could you check the value of `cortex_query_frontend_connected_clients`? It should be > 0 which indicates that some querier clients are connected to the frontend.

2) What liveness probe are you using on the container?

3) Another piece of info from some conversations in our slack channel - it appears that some platforms may not have private IPs available, in which case, the following config option needs to be manually configured:
```
    querier:
        frontend_worker:
            frontend_address: 127.0.0.1:9095
```

... it might be worth checking if that's the case and using another IP (POD IP? 0.0.0.0?) for the frontend address.

**Comment by mnadeem** [comment] 2021-02-01 15:29
I have used the following probes.

````
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /ready
                port: metrics
                scheme: HTTP
              initialDelaySeconds: 60
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 1
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /ready
                port: metrics
                scheme: HTTP
              initialDelaySeconds: 30
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 1
````

The details are documented in the following blog

https://reachmnadeem.wordpress.com/2021/01/30/distributed-tracing-using-grafana-tempo-jaeger-with-amazon-s3-as-backend-in-openshift-kubernetes/

**Comment by mnadeem** [comment] 2021-02-01 16:01
No luck with 

````
    querier:
        frontend_worker:
            frontend_address: 127.0.0.1:9095
````

````
auth_enabled: false

server:
  http_listen_port: 3100

distributor:
  receivers:                           # this configuration will listen on all ports and protocols that tempo is capable of.
    jaeger:                            # the receives all come from the OpenTelemetry collector.  more configuration information can
      protocols:                       # be found there: https://github.com/open-telemetry/opentelemetry-collector/tree/master/receiver
        thrift_http:                   #
        grpc:                          # for a production deployment you should only enable the receivers you need!
        thrift_binary:
        thrift_compact:
    zipkin:
    otlp:
      protocols:
        http:
        grpc:
    opencensus:

ingester:
  trace_idle_period: 10s               # the length of time after a trace has not received spans to consider it complete and flush it
  max_block_bytes: 100                 # cut the head block when it his this number of traces or ...
  #traces_per_block: 100
  max_block_duration: 5m               #   this much time passes

querier:
  frontend_worker:
    frontend_address: 127.0.0.1:9095

compactor:
  compaction:
    compaction_window: 1h              # blocks in this time window will be compacted together
    max_compaction_objects: 1000000    # maximum size of compacted blocks
    block_retention: 1h
    compacted_block_retention: 10m
    flush_size_bytes: 5242880

storage:
  trace:
    backend: s3                        # backend configuration to use
    wal:
      path: /tmp/tempo/wal             # where to store the the wal locally
      bloom_filter_false_positive: .05 # bloom filter false positive rate.  lower values create larger filters but fewer false positives
      index_downsample: 10             # number of traces per index record
    s3:
      endpoint: <endpoint>
      bucket: tempo                    # how to store data in s3
      access_key: <access_key>
      secret_key: <secret_key>
      insecure: false
    pool:
      max_workers: 100                 # the worker pool mainly drives querying, but is also used for polling the blocklist
      queue_depth: 10000

````

** log**

````
level=info ts=2021-02-01T15:56:34.311438452Z caller=main.go:89 msg="Starting Tempo" version="(version=4a1f2440, branch=master, revision=4a1f2440)"
level=info ts=2021-02-01T15:56:34.549440916Z caller=server.go:229 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2021-02-01T15:56:34.550563225Z caller=frontend.go:24 msg="creating tripperware in query frontend to shard queries"
level=info ts=2021-02-01T15:56:34.550985016Z caller=worker.go:112 msg="Starting querier worker connected to query-frontend" frontend=127.0.0.1:9095
ts=2021-02-01T15:56:34Z level=info msg="OTel Shim Logger Initialized" component=tempo
level=info ts=2021-02-01T15:56:34.55627961Z caller=module_service.go:58 msg=initialising module=overrides
level=info ts=2021-02-01T15:56:34.556285519Z caller=module_service.go:58 msg=initialising module=memberlist-kv
level=info ts=2021-02-01T15:56:34.556399141Z caller=module_service.go:58 msg=initialising module=store
level=info ts=2021-02-01T15:56:34.556495158Z caller=module_service.go:58 msg=initialising module=server
level=info ts=2021-02-01T15:56:34.556642787Z caller=module_service.go:58 msg=initialising module=ingester
level=info ts=2021-02-01T15:56:34.556657647Z caller=module_service.go:58 msg=initialising module=ring
level=info ts=2021-02-01T15:56:34.556650682Z caller=module_service.go:58 msg=initialising module=compactor
level=info ts=2021-02-01T15:56:34.556723766Z caller=compactor.go:95 msg="waiting for compaction ring to settle" waitDuration=1m0s
level=info ts=2021-02-01T15:56:34.556780353Z caller=module_service.go:58 msg=initialising module=query-frontend
level=info ts=2021-02-01T15:56:34.556876965Z caller=module_service.go:58 msg=initialising module=distributor
level=info ts=2021-02-01T15:56:34.556896256Z caller=client.go:242 msg="value is nil" key=collectors/ring index=1
level=info ts=2021-02-01T15:56:34.556935511Z caller=module_service.go:58 msg=initialising module=querier
level=info ts=2021-02-01T15:56:34.557002814Z caller=worker.go:192 msg="adding connection" addr=127.0.0.1:9095
level=info ts=2021-02-01T15:56:34.557303629Z caller=ingester.go:278 msg="beginning wal replay" numBlocks=0
level=info ts=2021-02-01T15:56:34.558594834Z caller=app.go:212 msg="Tempo started"
ts=2021-02-01T15:56:34Z level=info msg="No sampling strategies provided, using defaults" component=tempo
level=info ts=2021-02-01T15:56:34.55909702Z caller=lifecycler.go:521 msg="not loading tokens from file, tokens file path is empty"
level=info ts=2021-02-01T15:56:34.559231347Z caller=lifecycler.go:550 msg="instance not found in ring, adding with no tokens" ring=ingester
level=info ts=2021-02-01T15:56:34.55945366Z caller=lifecycler.go:397 msg="auto-joining cluster after timeout" ring=ingester
level=info ts=2021-02-01T15:57:34.556898707Z caller=compactor.go:97 msg="enabling compaction"
level=info ts=2021-02-01T15:57:34.556997565Z caller=tempodb.go:278 msg="compaction and retention enabled."
level=error ts=2021-02-01T15:57:34.571062873Z caller=frontend_processor.go:61 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"
level=error ts=2021-02-01T15:57:34.571094734Z caller=frontend_processor.go:61 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"
level=error ts=2021-02-01T15:57:34.571118299Z caller=frontend_processor.go:61 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"
level=error ts=2021-02-01T15:57:34.571143057Z caller=frontend_processor.go:61 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"
level=error ts=2021-02-01T15:57:34.571073287Z caller=frontend_processor.go:61 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"

````

**Comment by mdisibio** [comment] 2021-02-01 21:07
Adding some more findings here:   I believe the error message "error processing requests" is "normal" behavior, possibly new after the cortex 1.6 upgrade.   It appears to be logged if no queries are received within a period of time and the gRPC stream `recv` between querier and frontend times out.  The error message is logged here:  https://github.com/cortexproject/cortex/blob/v1.6.0/pkg/querier/worker/frontend_processor.go#L60


Using the docker-compose.yaml (local) example, and am able to lookup traces from the frontend and also get the error message when idle.  Example logs:
```
level=error ts=2021-02-01T20:58:18.560333511Z caller=frontend_processor.go:62 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"
....
level=info ts=2021-02-01T21:00:11.978496722Z caller=tempodb.go:249 org_id=single-tenant traceID=529bc66296bb66af msg="searching for trace in block" findTraceID=0000000000000000c6a759e023a461a2 block=9fa36a2b-cc1e-4267-be7b-500152314b83 found=false
level=info ts=2021-02-01T21:00:11.986720738Z caller=frontend.go:63 method=GET traceID=529bc66296bb66af url=/api/traces/c6a759e023a461a2 duration=11.722121ms status=200
```

**Comment by mnadeem** [comment] 2021-02-02 01:27
Interestingly things automatically started working like a charm now. Thanks a bundle

![image](https://user-images.githubusercontent.com/476145/106539389-e7abf880-6523-11eb-9887-0e8ce3daec8a.png)

**Comment by annanay25** [comment] 2021-02-03 12:32
I thought so too, I should look into the noisy error message. Changing the issue title to reflect that.

Thanks for reporting this, and all the best!

**Comment by annanay25** [comment] 2021-03-12 07:23
Closing this one as well as @mdisibio has dug into this and found the cause of the error messages.

**Comment by joe-elliott** [comment] 2021-03-12 15:40
@annanay25 I don't think we should close this.  the error message still exists and is confusing to people who think it's an actual problem.  

I think we should try to improve this message or maybe the docs surrounding it?

**Comment by dgzlopes** [comment] 2021-03-14 10:54
Today I was surfing my logs and saw this!

Having a `msg="error processing requests" ... err="rpc error: code = Unavailable desc = transport is closing"` logline is... scary :smile: 

If it's something normal, I think that improving the msg (as Joe suggests) or even changing the log level (error->info?) could be a good idea.

**Comment by annanay25** [comment] 2021-03-15 10:28
Haha okay fair, reopening.

**Comment by zswanson** [comment] 2021-03-27 15:27
> the error message still exists and is confusing to people who think it's an actual problem.

Its definitely confusing! I've been chasing my tail in my Fargate config for hours trying to figure out this "error" and then finally found this issue.

**Comment by eranrund** [comment] 2021-04-09 00:28
Also running into `caller=frontend_processor.go:59 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"` while trying the example from https://grafana.com/docs/tempo/latest/getting-started/ :(

**Comment by krikz** [comment] 2021-04-28 13:08
I have the same log and 404 for any trace, this is metrics (as described there https://grafana.com/docs/tempo/latest/troubleshooting/unable-to-see-trace/)
`
# HELP tempo_ingester_traces_created_total The total number of traces created per tenant.
# TYPE tempo_ingester_traces_created_total counter
tempo_ingester_traces_created_total{tenant="single-tenant"} 15
`
`
# HELP tempo_distributor_spans_received_total The total number of spans received per tenant
# TYPE tempo_distributor_spans_received_total counter
tempo_distributor_spans_received_total{tenant="single-tenant"} 15
`
![image](https://user-images.githubusercontent.com/5272634/116408358-5ce54c00-a83b-11eb-9c84-900fe79c3b6b.png)

`
level=error ts=2021-04-28T12:59:10.6765786Z caller=frontend_processor.go:59 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"
`
Look like something with frontend_processor, probably miss something in protocol on one side

**Closed** 2021-05-11 06:55 UTC

**Comment by sagarwala** [comment] 2021-08-23 10:55
I am seeing the same error logs with distributors with the v1.1.0-rc.1 release. Can someone please help me with this? 
```tempo level=error ts=2021-08-23T10:46:10.25888577Z caller=log.go:27 msg="pusher failed to consume trace data" err="rpc error: code = Unavailable desc = transport is closing"	
level=error ts=2021-08-23T10:46:10.157097875Z caller=log.go:27 msg="pusher failed to consume trace data" err="rpc error: code = Unavailable desc = transport is closing"
level=warn ts=2021-08-23T10:46:09.836463272Z caller=pool.go:185 msg="removing distributor_pool failing healthcheck" addr=10.58.21.174:9095 reason="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
ts=2021-08-23T10:46:05.813528284Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: read tcp 10.58.14.31:42490->10.58.44.61:7946: i/o timeout"	
level=warn ts=2021-08-23T10:46:02.153600971Z caller=pool.go:185 msg="removing distributor_pool failing healthcheck" addr=10.58.26.235:9095 reason="rpc error: code = DeadlineExceeded desc = context deadline exceeded"	
level=error ts=2021-08-23T10:45:55.258558135Z caller=log.go:27 msg="pusher failed to consume trace data" err="rpc error: code = Unavailable desc = transport is closing"	
level=warn ts=2021-08-23T10:45:55.048372224Z caller=pool.go:185 msg="removing distributor_pool failing healthcheck" addr=10.58.26.41:9095 reason="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
level=error ts=2021-08-23T10:45:35.558405519Z caller=log.go:27 msg="pusher failed to consume trace data" err="rpc error: code = Unavailable desc = transport is closing"

**Comment by joe-elliott** [comment] 2021-08-24 13:23
@sagarwala you are seeing a different issue. It looks like your distributors are failing to connect to your ingesters. I would suggest posting a question here:

https://community.grafana.com/c/grafana-tempo/40
